// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Deterministic C code generator for lustreiser.
//
// Generates C99 code from parsed Lustre node definitions. The generated code
// follows the standard Lustre-to-C compilation pattern:
//
//   1. A state struct holding all delay-line values (pre/fby state)
//   2. An init function to zero-initialise the state
//   3. A step function called once per clock tick:
//      - Reads inputs
//      - Computes outputs deterministically from inputs + state
//      - Updates state for the next tick
//
// The generated C is suitable for bare-metal embedded targets (no heap,
// no dynamic dispatch, bounded stack, deterministic execution time).

use super::parser::ParsedNode;
use crate::abi::SignalType;
use crate::manifest::Manifest;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Generate a C header (.h) and source (.c) file for a single node.
/// Returns (header_content, source_content).
pub fn generate_c_node(node: &ParsedNode, manifest: &Manifest) -> (String, String) {
    let header = generate_header(node, manifest);
    let source = generate_source(node, manifest);
    (header, source)
}

// ---------------------------------------------------------------------------
// Header generation
// ---------------------------------------------------------------------------

/// Generate the C header file (.h) for a node.
///
/// Contains:
///   - Include guard
///   - State struct typedef
///   - Init function prototype
///   - Step function prototype
fn generate_header(node: &ParsedNode, manifest: &Manifest) -> String {
    let guard = format!("{}_H", node.name.to_uppercase());
    let mut buf = String::with_capacity(2048);

    // File header.
    buf.push_str(&format!(
        "/* Generated by lustreiser — DO NOT EDIT */\n\
         /* SPDX-License-Identifier: PMPL-1.0-or-later */\n\
         /* Node: {} | Target: {} | Standard: {} */\n\n",
        node.name, manifest.target.platform, manifest.target.safety_standard,
    ));

    // Include guard.
    buf.push_str(&format!("#ifndef {}\n#define {}\n\n", guard, guard));

    // Required headers.
    buf.push_str("#include <stdint.h>\n");
    buf.push_str("#include <stdbool.h>\n\n");

    // State struct: holds all delay-line values for fby/pre operators.
    buf.push_str(&format!("/**\n * State struct for node '{}'.\n", node.name));
    buf.push_str(" * Holds delay-line values for temporal operators (pre/fby).\n");
    buf.push_str(&format!(
        " * Base clock: {}ms ({:.1}Hz)\n */\n",
        node.clock.base_period_ms,
        node.clock.frequency_hz(),
    ));
    buf.push_str(&format!("typedef struct {{\n"));

    // One state field per output (for fby previous value).
    for output in &node.outputs {
        buf.push_str(&format!(
            "    {} {}_prev;  /**< Previous value of output '{}' */\n",
            output.signal_type.c_type(),
            output.name,
            output.name,
        ));
    }

    // Tick counter for multi-rate scheduling.
    if node.is_multi_rate {
        buf.push_str("    uint32_t tick_count;  /**< Base-clock tick counter for rate division */\n");
    }

    // Initialisation flag.
    buf.push_str("    bool _initialised;  /**< Whether init has been called */\n");

    buf.push_str(&format!("}} {}_state_t;\n\n", node.name));

    // Input struct.
    buf.push_str(&format!("/**\n * Input signals for node '{}'.\n */\n", node.name));
    buf.push_str(&format!("typedef struct {{\n"));
    for input in &node.inputs {
        buf.push_str(&format!(
            "    {} {};  /**< Input signal '{}' (rate: /{}) */\n",
            input.signal_type.c_type(),
            input.name,
            input.name,
            input.rate,
        ));
    }
    buf.push_str(&format!("}} {}_input_t;\n\n", node.name));

    // Output struct.
    buf.push_str(&format!("/**\n * Output signals for node '{}'.\n */\n", node.name));
    buf.push_str(&format!("typedef struct {{\n"));
    for output in &node.outputs {
        buf.push_str(&format!(
            "    {} {};  /**< Output signal '{}' */\n",
            output.signal_type.c_type(),
            output.name,
            output.name,
        ));
    }
    buf.push_str(&format!("}} {}_output_t;\n\n", node.name));

    // Function prototypes.
    buf.push_str(&format!(
        "/**\n * Initialise the state struct for node '{}'.\n",
        node.name
    ));
    buf.push_str(" * MUST be called exactly once before the first step.\n */\n");
    buf.push_str(&format!(
        "void {}_init({}_state_t *state);\n\n",
        node.name, node.name,
    ));

    buf.push_str(&format!(
        "/**\n * Execute one step of node '{}'.\n",
        node.name
    ));
    buf.push_str(&format!(
        " * Called once per base-clock tick (every {}ms).\n",
        node.clock.base_period_ms,
    ));
    buf.push_str(" * Deterministic: same inputs + state => same outputs.\n");
    buf.push_str(&format!(
        " * WCET budget: {}us deadline.\n */\n",
        manifest.timing.deadline_us,
    ));
    buf.push_str(&format!(
        "void {}_step(\n    {}_state_t *state,\n    const {}_input_t *input,\n    {}_output_t *output\n);\n\n",
        node.name, node.name, node.name, node.name,
    ));

    buf.push_str(&format!("#endif /* {} */\n", guard));

    buf
}

// ---------------------------------------------------------------------------
// Source generation
// ---------------------------------------------------------------------------

/// Generate the C source file (.c) for a node.
///
/// Contains:
///   - Init function implementation
///   - Step function implementation with deterministic equations
fn generate_source(node: &ParsedNode, manifest: &Manifest) -> String {
    let mut buf = String::with_capacity(4096);

    // File header.
    buf.push_str(&format!(
        "/* Generated by lustreiser — DO NOT EDIT */\n\
         /* SPDX-License-Identifier: PMPL-1.0-or-later */\n\
         /* Node: {} | Target: {} | Standard: {} */\n\n",
        node.name, manifest.target.platform, manifest.target.safety_standard,
    ));

    buf.push_str(&format!("#include \"{}.h\"\n\n", node.name));

    // Init function.
    buf.push_str(&format!(
        "void {}_init({}_state_t *state) {{\n",
        node.name, node.name,
    ));
    for output in &node.outputs {
        buf.push_str(&format!(
            "    state->{}_prev = {};\n",
            output.name,
            c_default_value(&output.signal_type),
        ));
    }
    if node.is_multi_rate {
        buf.push_str("    state->tick_count = 0;\n");
    }
    buf.push_str("    state->_initialised = true;\n");
    buf.push_str("}\n\n");

    // Step function.
    buf.push_str(&format!(
        "void {}_step(\n    {}_state_t *state,\n    const {}_input_t *input,\n    {}_output_t *output\n) {{\n",
        node.name, node.name, node.name, node.name,
    ));

    if node.is_multi_rate {
        // Multi-rate: use tick counter for rate division.
        buf.push_str("    /* Multi-rate clock division */\n");
        buf.push_str("    state->tick_count++;\n\n");

        for (i, output) in node.outputs.iter().enumerate() {
            if i < node.inputs.len() {
                let input_sig = &node.inputs[i];
                if input_sig.rate > 1 {
                    // Sub-rate input: only sample when tick aligns.
                    buf.push_str(&format!(
                        "    /* Rate division: sample '{}' every {} ticks */\n",
                        input_sig.name, input_sig.rate,
                    ));
                    buf.push_str(&format!(
                        "    if (state->tick_count % {} == 0) {{\n",
                        input_sig.rate,
                    ));
                    buf.push_str(&format!(
                        "        output->{} = input->{};\n",
                        output.name, input_sig.name,
                    ));
                    buf.push_str("    } else {\n");
                    buf.push_str(&format!(
                        "        output->{} = state->{}_prev;\n",
                        output.name, output.name,
                    ));
                    buf.push_str("    }\n");
                } else {
                    // Base-rate input: pass through with accumulation.
                    buf.push_str(&format!(
                        "    output->{} = input->{} + state->{}_prev;\n",
                        output.name, input_sig.name, output.name,
                    ));
                }
            } else {
                buf.push_str(&format!(
                    "    output->{} = state->{}_prev;\n",
                    output.name, output.name,
                ));
            }
        }
    } else {
        // Single-rate: straightforward computation.
        buf.push_str("    /* Single-rate: all signals at base clock */\n");
        for (i, output) in node.outputs.iter().enumerate() {
            if i < node.inputs.len() {
                let input_sig = &node.inputs[i];
                buf.push_str(&format!(
                    "    output->{} = input->{} + state->{}_prev;\n",
                    output.name, input_sig.name, output.name,
                ));
            } else if !node.inputs.is_empty() {
                let last_input = &node.inputs[node.inputs.len() - 1];
                buf.push_str(&format!(
                    "    output->{} = input->{} + state->{}_prev;\n",
                    output.name, last_input.name, output.name,
                ));
            }
        }
    }

    // Update state (fby: store current output as previous for next tick).
    buf.push_str("\n    /* Update delay lines (fby state) */\n");
    for output in &node.outputs {
        buf.push_str(&format!(
            "    state->{}_prev = output->{};\n",
            output.name, output.name,
        ));
    }

    buf.push_str("}\n");

    buf
}

/// Return the C default value literal for a signal type.
fn c_default_value(signal_type: &SignalType) -> &'static str {
    match signal_type {
        SignalType::Bool => "false",
        SignalType::Int => "0",
        SignalType::Float => "0.0f",
        SignalType::Real => "0.0",
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::abi::{Clock, Signal, SignalType};
    use crate::manifest::*;

    fn test_manifest() -> Manifest {
        Manifest {
            project: ProjectConfig {
                name: "test".to_string(),
                version: "0.1.0".to_string(),
            },
            nodes: vec![NodeConfig {
                name: "ctrl".to_string(),
                inputs: vec!["x:real".to_string()],
                outputs: vec!["y:real".to_string()],
                clock: ClockConfig { base_period_ms: 10 },
            }],
            target: TargetConfig {
                platform: "arm-cortex-m".to_string(),
                safety_standard: "DO-178C".to_string(),
            },
            timing: TimingConfig {
                deadline_us: 5000,
                wcet_analysis: true,
            },
            workload: None,
            data: None,
            options: None,
        }
    }

    fn simple_node() -> ParsedNode {
        ParsedNode {
            name: "ctrl".to_string(),
            inputs: vec![Signal::new("x", SignalType::Real)],
            outputs: vec![Signal::new("y", SignalType::Real)],
            clock: Clock::new(10).unwrap(),
            operator_count: 1,
            is_multi_rate: false,
        }
    }

    #[test]
    fn test_header_include_guard() {
        let (header, _) = generate_c_node(&simple_node(), &test_manifest());
        assert!(header.contains("#ifndef CTRL_H"));
        assert!(header.contains("#define CTRL_H"));
        assert!(header.contains("#endif"));
    }

    #[test]
    fn test_header_state_struct() {
        let (header, _) = generate_c_node(&simple_node(), &test_manifest());
        assert!(header.contains("ctrl_state_t"));
        assert!(header.contains("double y_prev"));
        assert!(header.contains("bool _initialised"));
    }

    #[test]
    fn test_header_io_structs() {
        let (header, _) = generate_c_node(&simple_node(), &test_manifest());
        assert!(header.contains("ctrl_input_t"));
        assert!(header.contains("ctrl_output_t"));
        assert!(header.contains("double x;"));
        assert!(header.contains("double y;"));
    }

    #[test]
    fn test_header_function_prototypes() {
        let (header, _) = generate_c_node(&simple_node(), &test_manifest());
        assert!(header.contains("void ctrl_init(ctrl_state_t *state)"));
        assert!(header.contains("void ctrl_step("));
    }

    #[test]
    fn test_source_init_function() {
        let (_, source) = generate_c_node(&simple_node(), &test_manifest());
        assert!(source.contains("void ctrl_init(ctrl_state_t *state)"));
        assert!(source.contains("state->y_prev = 0.0"));
        assert!(source.contains("state->_initialised = true"));
    }

    #[test]
    fn test_source_step_function() {
        let (_, source) = generate_c_node(&simple_node(), &test_manifest());
        assert!(source.contains("void ctrl_step("));
        assert!(source.contains("output->y = input->x + state->y_prev"));
        assert!(source.contains("state->y_prev = output->y"));
    }

    #[test]
    fn test_source_spdx() {
        let (_, source) = generate_c_node(&simple_node(), &test_manifest());
        assert!(source.contains("SPDX-License-Identifier: PMPL-1.0-or-later"));
    }

    #[test]
    fn test_multi_rate_tick_counter() {
        let node = ParsedNode {
            name: "mrate".to_string(),
            inputs: vec![
                Signal::new("fast", SignalType::Real),
                Signal::with_rate("slow", SignalType::Real, 5),
            ],
            outputs: vec![
                Signal::new("out_fast", SignalType::Real),
                Signal::new("out_slow", SignalType::Real),
            ],
            clock: Clock::new(10).unwrap(),
            operator_count: 3,
            is_multi_rate: true,
        };
        let (header, source) = generate_c_node(&node, &test_manifest());
        assert!(header.contains("uint32_t tick_count"));
        assert!(source.contains("tick_count"));
        assert!(source.contains("% 5"));
    }

    #[test]
    fn test_bool_signal_c_type() {
        let node = ParsedNode {
            name: "latch".to_string(),
            inputs: vec![Signal::new("trigger", SignalType::Bool)],
            outputs: vec![Signal::new("held", SignalType::Bool)],
            clock: Clock::new(1).unwrap(),
            operator_count: 1,
            is_multi_rate: false,
        };
        let (header, source) = generate_c_node(&node, &test_manifest());
        assert!(header.contains("_Bool trigger"));
        assert!(header.contains("_Bool held"));
        assert!(source.contains("state->held_prev = false"));
    }
}
