// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Lustre (.lus) file generator for lustreiser.
//
// Generates syntactically correct Lustre V6 source files from parsed node
// definitions. Each node is emitted with:
//   - Typed input/output declarations
//   - Clock annotations for multi-rate signals
//   - Temporal operators (pre, fby, when, merge) for state and sampling
//   - Deterministic equations binding outputs to expressions
//
// The generated Lustre can be fed to lv6, kind2, or Scade for further
// verification and compilation.

use super::parser::ParsedNode;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Generate a complete Lustre (.lus) source file for a single node.
///
/// The output is a self-contained .lus file that can be compiled by any
/// Lustre V6-compatible tool (lv6, kind2, Scade Suite).
pub fn generate_lustre_node(node: &ParsedNode) -> String {
    let mut buf = String::with_capacity(2048);

    // File header comment.
    buf.push_str(&format!(
        "-- Generated by lustreiser — DO NOT EDIT\n\
         -- SPDX-License-Identifier: PMPL-1.0-or-later\n\
         -- Node: {}\n\
         -- Base clock: {}ms ({:.1}Hz)\n\n",
        node.name,
        node.clock.base_period_ms,
        node.clock.frequency_hz(),
    ));

    // Node declaration.
    buf.push_str(&format!("node {}(\n", node.name));

    // Input declarations.
    for (i, input) in node.inputs.iter().enumerate() {
        let separator = if i < node.inputs.len() - 1 { ";" } else { "" };
        if input.rate > 1 {
            // Multi-rate input: annotate with clock constraint comment.
            buf.push_str(&format!(
                "  {}: {} -- @/{} (sampled every {} base ticks){}\n",
                input.name,
                input.signal_type.lustre_type(),
                input.rate,
                input.rate,
                separator,
            ));
        } else {
            buf.push_str(&format!(
                "  {}: {}{}\n",
                input.name,
                input.signal_type.lustre_type(),
                separator,
            ));
        }
    }

    // Returns clause.
    buf.push_str(") returns (\n");

    // Output declarations.
    for (i, output) in node.outputs.iter().enumerate() {
        let separator = if i < node.outputs.len() - 1 { ";" } else { "" };
        buf.push_str(&format!(
            "  {}: {}{}\n",
            output.name,
            output.signal_type.lustre_type(),
            separator,
        ));
    }

    buf.push_str(");\n");

    // Local variable declarations (for temporal operators).
    let locals = generate_locals(node);
    if !locals.is_empty() {
        buf.push_str("var\n");
        for local in &locals {
            buf.push_str(&format!("  {};\n", local));
        }
    }

    // Equation body.
    buf.push_str("let\n");

    let equations = generate_equations(node);
    for eq in &equations {
        buf.push_str(&format!("  {};\n", eq));
    }

    buf.push_str("tel\n");

    buf
}

// ---------------------------------------------------------------------------
// Local variable generation
// ---------------------------------------------------------------------------

/// Generate local variable declarations needed for temporal operators.
///
/// For each output, we may need:
///   - A `_prev` variable for `pre` / `fby` delay lines
///   - A `_sampled` variable for `when` down-sampling
fn generate_locals(node: &ParsedNode) -> Vec<String> {
    let mut locals = Vec::new();

    // Each output gets a previous-value local for the fby operator.
    for output in &node.outputs {
        locals.push(format!(
            "{}_prev: {}",
            output.name,
            output.signal_type.lustre_type()
        ));
    }

    // Multi-rate inputs get a sampled local for the when operator.
    if node.is_multi_rate {
        for input in &node.inputs {
            if input.rate > 1 {
                locals.push(format!(
                    "{}_sampled: {}",
                    input.name,
                    input.signal_type.lustre_type()
                ));
            }
        }

        // Clock selector boolean for merge operations.
        locals.push("clk_sel: bool".to_string());
    }

    locals
}

// ---------------------------------------------------------------------------
// Equation generation
// ---------------------------------------------------------------------------

/// Generate the body equations for a Lustre node.
///
/// Strategy:
/// - Single-rate: direct pass-through with fby for state
/// - Multi-rate: when/merge clock calculus for rate adaptation
fn generate_equations(node: &ParsedNode) -> Vec<String> {
    let mut equations = Vec::new();

    if node.is_multi_rate {
        // Generate clock selector based on a tick counter.
        // In real Lustre, clocks are inferred; here we make them explicit
        // for clarity and traceability.
        equations.push("-- Clock calculus: multi-rate signal adaptation".to_string());

        // Generate when-sampled locals for sub-rate inputs.
        for input in &node.inputs {
            if input.rate > 1 {
                equations.push(format!(
                    "{}_sampled = {} when clk_sel",
                    input.name, input.name,
                ));
            }
        }

        // Generate output equations using merge to combine rates.
        for (i, output) in node.outputs.iter().enumerate() {
            let init_val = default_init_value(&output.signal_type);

            // fby for state tracking.
            equations.push(format!(
                "{}_prev = {} fby {}",
                output.name, init_val, output.name,
            ));

            // Output equation: combine inputs.
            // For the first output, sum/average all inputs.
            // For subsequent outputs, use the corresponding input if available.
            if i < node.inputs.len() {
                let input = &node.inputs[i];
                if input.rate > 1 {
                    equations.push(format!(
                        "{} = merge(clk_sel, {}_sampled, {}_prev)",
                        output.name, input.name, output.name,
                    ));
                } else {
                    equations.push(format!(
                        "{} = {} + {}_prev",
                        output.name, input.name, output.name,
                    ));
                }
            } else {
                equations.push(format!(
                    "{} = {}_prev",
                    output.name, output.name,
                ));
            }
        }
    } else {
        // Single-rate: straightforward equations.
        equations.push("-- Single-rate node: all signals at base clock".to_string());

        for (i, output) in node.outputs.iter().enumerate() {
            let init_val = default_init_value(&output.signal_type);

            // fby for previous value (unit delay for state).
            equations.push(format!(
                "{}_prev = {} fby {}",
                output.name, init_val, output.name,
            ));

            // Output = f(inputs, prev_state).
            // Default: pass first input through with accumulation via prev.
            if i < node.inputs.len() {
                let input = &node.inputs[i];
                equations.push(format!(
                    "{} = {} + {}_prev",
                    output.name, input.name, output.name,
                ));
            } else if !node.inputs.is_empty() {
                // Reuse last input for extra outputs.
                let last_input = &node.inputs[node.inputs.len() - 1];
                equations.push(format!(
                    "{} = {} + {}_prev",
                    output.name, last_input.name, output.name,
                ));
            }
        }
    }

    equations
}

/// Return the default initialisation value for a signal type.
/// Used in `fby` expressions: `init fby stream`.
fn default_init_value(signal_type: &crate::abi::SignalType) -> &'static str {
    use crate::abi::SignalType;
    match signal_type {
        SignalType::Bool => "false",
        SignalType::Int => "0",
        SignalType::Float => "0.0",
        SignalType::Real => "0.0",
    }
}

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::abi::{Clock, Signal, SignalType};

    /// Helper: build a simple single-rate node.
    fn simple_node() -> ParsedNode {
        ParsedNode {
            name: "integrator".to_string(),
            inputs: vec![Signal::new("x", SignalType::Real)],
            outputs: vec![Signal::new("y", SignalType::Real)],
            clock: Clock::new(10).unwrap(),
            operator_count: 1,
            is_multi_rate: false,
        }
    }

    #[test]
    fn test_lustre_node_header() {
        let lus = generate_lustre_node(&simple_node());
        assert!(lus.contains("node integrator("));
        assert!(lus.contains("x: real"));
        assert!(lus.contains("y: real"));
        assert!(lus.contains("returns"));
        assert!(lus.contains("let"));
        assert!(lus.contains("tel"));
    }

    #[test]
    fn test_lustre_fby_present() {
        let lus = generate_lustre_node(&simple_node());
        assert!(lus.contains("fby"), "Expected fby operator in generated Lustre");
    }

    #[test]
    fn test_lustre_multi_rate_when_merge() {
        // The sub-rate input ("slow") must be the first input so it maps to
        // the first output and triggers merge in the equation.
        let node = ParsedNode {
            name: "multi".to_string(),
            inputs: vec![
                Signal::with_rate("slow", SignalType::Real, 10),
                Signal::new("fast", SignalType::Real),
            ],
            outputs: vec![
                Signal::new("out_slow", SignalType::Real),
                Signal::new("out_fast", SignalType::Real),
            ],
            clock: Clock::new(5).unwrap(),
            operator_count: 3,
            is_multi_rate: true,
        };
        let lus = generate_lustre_node(&node);
        assert!(lus.contains("when"), "Expected 'when' operator for multi-rate");
        assert!(lus.contains("merge"), "Expected 'merge' operator for multi-rate");
        assert!(lus.contains("slow_sampled"), "Expected sampled local for sub-rate input");
    }

    #[test]
    fn test_lustre_local_variables() {
        let lus = generate_lustre_node(&simple_node());
        assert!(lus.contains("var"), "Expected var block for locals");
        assert!(lus.contains("y_prev: real"), "Expected y_prev local");
    }

    #[test]
    fn test_lustre_spdx_header() {
        let lus = generate_lustre_node(&simple_node());
        assert!(lus.contains("SPDX-License-Identifier: PMPL-1.0-or-later"));
    }

    #[test]
    fn test_lustre_bool_init_value() {
        let node = ParsedNode {
            name: "latch".to_string(),
            inputs: vec![Signal::new("trigger", SignalType::Bool)],
            outputs: vec![Signal::new("held", SignalType::Bool)],
            clock: Clock::new(1).unwrap(),
            operator_count: 1,
            is_multi_rate: false,
        };
        let lus = generate_lustre_node(&node);
        assert!(lus.contains("false fby"), "Expected 'false fby' for bool init");
    }
}
